[options]
admin_passwd = odoo
addons_path = /home/wai-phyo-htet/Documents/Owl-Training/source_code/odoo19e_dec18/odoo/addons,/home/wai-phyo-htet/Documents/Owl-Training/addons
db_host = localhost
db_user = odoo
db_password = odoo
db_name = owl_test_db
